// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package go_shop

import (
	"github.com/gin-gonic/gin"
	"go-shop/internal/repository/dao"
	"go-shop/internal/service"
	"go-shop/internal/startup"
	startup2 "go-shop/pkg/ginx"
)

// Injectors from wire.go:

// InitializeProductRouter 初始化 Product 相关的 Gin 路由
func InitializeProductRouter() *gin.Engine {
	v := startup.InitGinMiddlewares()
	db := startup.GetDB()
	productDao := dao.NewProductDao(db)
	productService := service.NewProductService(productDao)
	engine := startup2.NewGinEngine(v, productService)
	return engine
}
