// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package go_shop

import (
	"github.com/gin-gonic/gin"
	"go-shop/internal/repository/dao"
	"go-shop/internal/routers"
	"go-shop/internal/service"
	"go-shop/internal/startup"
)

// Injectors from wire.go:

// 初始化依赖注入
func InitializeProductRouter() *gin.Engine {
	db := startup.GetDB()
	productDao := dao.NewProductDao(db)
	productService := service.NewProductService(productDao)
	engine := routers.NewRouter(productService)
	return engine
}
